# radium completion                                        -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_radium_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compline="${COMP_WORDS[@]:1:$COMP_CWORD-1}"

  case "$compline" in
    'remove-mirror'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -A index -- "$cur" )
      ;;

    'add-mirror'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -A url -- "$cur" )
      ;;

    'install'*)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -A package -- "$cur" )
      ;;

    *)
      while read; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "add-mirror remove-mirror list-mirrors install" -- "$cur" )
      ;;

  esac
} &&
complete -F _radium_completions radium

# ex: filetype=sh
